import mongoose from 'mongoose';

const nurseSchema = new mongoose.Schema({
  hospital: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    unique: true
  },
  employeeId: {
    type: String,
    required: false, // Will be auto-generated by pre-save hook
    unique: true,
    trim: true
    // Index created at schema level below
  },
  firstName: {
    type: String,
    required: true,
    trim: true
  },
  lastName: {
    type: String,
    required: true,
    trim: true
  },
  email: {
    type: String,
    required: true,
    unique: true,
    lowercase: true,
    trim: true
  },
  phone: {
    type: String,
    required: true,
    trim: true
  },
  department: {
    type: String,
    required: true,
    trim: true
  },
  specialization: {
    type: String,
    trim: true
  },
  licenseNumber: {
    type: String,
    required: true,
    unique: true,
    trim: true
  },
  qualifications: [{
    degree: String,
    institution: String,
    year: Number
  }],
  experience: {
    type: Number,
    default: 0,
    min: 0
  },
  shift: {
    type: String,
    enum: ['day', 'night', 'rotating', 'evening'], // Added 'evening' to support frontend
    default: 'day'
  },
  status: {
    type: String,
    enum: ['active', 'inactive', 'on_leave', 'terminated'],
    default: 'active'
  },
  hireDate: {
    type: Date,
    default: Date.now
  },
  address: {
    street: String,
    city: String,
    state: String,
    zipCode: String,
    country: String
  },
  emergencyContact: {
    name: String,
    relationship: String,
    phone: String
  },
  profilePicture: {
    type: String,
    trim: true
  },
  notes: {
    type: String,
    trim: true
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  updatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true
});

// Indexes
nurseSchema.index({ hospital: 1, status: 1 });
nurseSchema.index({ hospital: 1, department: 1 });
// employeeId already has unique index from unique: true

// Generate employee ID before saving
nurseSchema.pre('save', async function(next) {
  // Only generate if this is a new document and employeeId is not set
  if (this.isNew && !this.employeeId) {
    try {
      const NurseModel = mongoose.model('Nurse');
      const count = await NurseModel.countDocuments({ hospital: this.hospital });
      this.employeeId = `NURSE-${String(count + 1).padStart(4, '0')}`;
    } catch (error) {
      // Fallback if count fails
      this.employeeId = `NURSE-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
    }
  }
  next();
});

const Nurse = mongoose.model('Nurse', nurseSchema);

export default Nurse;

